/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.controller.ItemController;
import lk.ijse.controller.ItemDetailController;
import lk.ijse.controller.SuplierController;
import lk.ijse.model.Items;
import lk.ijse.model.Supliers;
import lk.ijse.model.itemDetail;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author kushantha
 */
public class AddedQty extends javax.swing.JFrame {

    /**
     * Creates new form AddedQty
     */
    public AddedQty() {
        try {
            initComponents();
            loadSuplierId();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            AutoCompleteDecorator.decorate(comboItemId);
            AutoCompleteDecorator.decorate(comboSuplierId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNoOfBundle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        calculateQty = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBuyingPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        comboSuplierId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboItemId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtQtyInBundle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Added Quantity");

        jPanel1.setBackground(new java.awt.Color(19, 15, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtDescription.setBackground(new java.awt.Color(19, 15, 64));
        txtDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        txtDescription.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 229, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No of Bundle");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        txtNoOfBundle.setBackground(new java.awt.Color(19, 15, 64));
        txtNoOfBundle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNoOfBundle.setForeground(new java.awt.Color(255, 255, 255));
        txtNoOfBundle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNoOfBundle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        txtNoOfBundle.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtNoOfBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfBundleActionPerformed(evt);
            }
        });
        txtNoOfBundle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoOfBundleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfBundleKeyReleased(evt);
            }
        });
        jPanel1.add(txtNoOfBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 229, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Calculate Qty");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        calculateQty.setBackground(new java.awt.Color(19, 15, 64));
        calculateQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        calculateQty.setForeground(new java.awt.Color(255, 255, 255));
        calculateQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        calculateQty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        calculateQty.setSelectionColor(new java.awt.Color(0, 0, 204));
        calculateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateQtyActionPerformed(evt);
            }
        });
        jPanel1.add(calculateQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 229, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("buying price");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        txtBuyingPrice.setBackground(new java.awt.Color(19, 15, 64));
        txtBuyingPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuyingPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtBuyingPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuyingPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        txtBuyingPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBuyingPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuyingPriceMouseClicked(evt);
            }
        });
        txtBuyingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingPriceActionPerformed(evt);
            }
        });
        txtBuyingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuyingPriceKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuyingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 229, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtTotal.setBackground(new java.awt.Color(19, 15, 64));
        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        txtTotal.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 229, -1));

        jButton7.setBackground(new java.awt.Color(153, 0, 0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_add_new_52px_1.png"))); // NOI18N
        jButton7.setText("Add");
        jButton7.setIconTextGap(1);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 190, 60));

        comboSuplierId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboSuplierId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Suplier ID" }));
        comboSuplierId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSuplierIdItemStateChanged(evt);
            }
        });
        comboSuplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSuplierIdActionPerformed(evt);
            }
        });
        jPanel1.add(comboSuplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 230, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qty in Bundle");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        comboItemId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboItemId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selected Item" }));
        comboItemId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemIdItemStateChanged(evt);
            }
        });
        comboItemId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemIdMouseClicked(evt);
            }
        });
        comboItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemIdActionPerformed(evt);
            }
        });
        jPanel1.add(comboItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Suplier Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        txtQtyInBundle.setBackground(new java.awt.Color(19, 15, 64));
        txtQtyInBundle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQtyInBundle.setForeground(new java.awt.Color(255, 255, 255));
        txtQtyInBundle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtyInBundle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 255, 126)));
        txtQtyInBundle.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtQtyInBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyInBundleActionPerformed(evt);
            }
        });
        txtQtyInBundle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyInBundleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyInBundleKeyReleased(evt);
            }
        });
        jPanel1.add(txtQtyInBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 229, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("N/A");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        txtQtyInBundle.requestFocus();
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtNoOfBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfBundleActionPerformed
        txtBuyingPrice.requestFocus();

    }//GEN-LAST:event_txtNoOfBundleActionPerformed

    private void txtNoOfBundleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfBundleKeyPressed

    }//GEN-LAST:event_txtNoOfBundleKeyPressed

    private void txtNoOfBundleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfBundleKeyReleased
        try {
            int qtyInBundle = Integer.parseInt(txtQtyInBundle.getText());

            int noOfBundle = Integer.parseInt(txtNoOfBundle.getText());

            int totalQty = qtyInBundle * noOfBundle;
            calculateQty.setText(Integer.toString(totalQty));
        }catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_txtNoOfBundleKeyReleased

    private void calculateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateQtyActionPerformed

    }//GEN-LAST:event_calculateQtyActionPerformed

    private void txtBuyingPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuyingPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyingPriceMouseClicked

    private void txtBuyingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingPriceActionPerformed


    }//GEN-LAST:event_txtBuyingPriceActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            int qty = Integer.parseInt(calculateQty.getText());
            String item = comboItemId.getSelectedItem().toString();
            String supId = comboSuplierId.getSelectedItem().toString();
            double total = Double.parseDouble(txtTotal.getText());
            itemDetail detail = new itemDetail(item, supId, total, qty);

            Object isAdded = new ItemDetailController().addItems(detail);
            if(isAdded != null){
                clear();
                JOptionPane.showMessageDialog(null, "Added quantity");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void comboSuplierIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSuplierIdItemStateChanged

        try {

            String supId = (String) comboSuplierId.getSelectedItem();
//            new ItemDetailController().getItem(supId);
            Supliers suplier = new SuplierController().getSupliers(supId);
            lblName.setText(suplier.getSupName());
            for (String id : new ItemDetailController().getItem(supId)) {
                comboItemId.addItem(id);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_comboSuplierIdItemStateChanged

    private void comboSuplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSuplierIdActionPerformed

    }//GEN-LAST:event_comboSuplierIdActionPerformed

    private void comboItemIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemIdItemStateChanged

    }//GEN-LAST:event_comboItemIdItemStateChanged

    private void comboItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemIdActionPerformed
        if (comboItemId.getItemCount() != 0) {
            try {
                String itemId = (String) comboItemId.getSelectedItem();
                Items description = new ItemController().getDescription2(itemId);
                txtDescription.setText(description.getDescription());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AddedQty.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboItemIdActionPerformed

    private void txtQtyInBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyInBundleActionPerformed
        txtNoOfBundle.requestFocus();
    }//GEN-LAST:event_txtQtyInBundleActionPerformed

    private void txtBuyingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuyingPriceKeyReleased
        try {
        int totalQty = Integer.parseInt(calculateQty.getText());
        double buyPrice = Double.parseDouble(txtBuyingPrice.getText());

        double total = totalQty * buyPrice;
        txtTotal.setText(Double.toString(total));
        }catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_txtBuyingPriceKeyReleased

    private void txtQtyInBundleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyInBundleKeyReleased

    }//GEN-LAST:event_txtQtyInBundleKeyReleased

    private void txtQtyInBundleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyInBundleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyInBundleKeyPressed

    private void comboItemIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemIdMouseClicked

    }//GEN-LAST:event_comboItemIdMouseClicked
    private void clear(){
        txtDescription.setText("");
        txtQtyInBundle.setText("");
        txtNoOfBundle.setText("");
        calculateQty.setText("");
        txtBuyingPrice.setText("");
        txtTotal.setText("");
        
    }
    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        
    }//GEN-LAST:event_jButton7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddedQty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddedQty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddedQty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddedQty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddedQty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calculateQty;
    public static javax.swing.JComboBox<String> comboItemId;
    private javax.swing.JComboBox<String> comboSuplierId;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtBuyingPrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNoOfBundle;
    private javax.swing.JTextField txtQtyInBundle;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void loadSuplierId() throws ClassNotFoundException, SQLException {

        for (String temp : new SuplierController().getAllId()) {
            comboSuplierId.addItem(temp);
        }

    }
}
