/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.controller.ItemController;
import lk.ijse.controller.SuplierController;

import lk.ijse.model.Items;

import lk.ijse.model.Supliers;

/**
 *
 * @author kushantha
 */
public class AddsupandItem extends javax.swing.JFrame {

    /**
     * Creates new form AddsupandItem
     */
    public AddsupandItem() throws ClassNotFoundException, SQLException {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadSuplierId();
        loadItemId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtSupId = new javax.swing.JTextField();
        txtSupName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSuoContact = new javax.swing.JTextField();
        txtSupAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        txtBarcodeId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAuthorName = new javax.swing.JTextField();
        txtPname = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rSchoolStationery = new javax.swing.JRadioButton();
        rOthers = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtBuyingPrice = new javax.swing.JTextField();
        buyinPrice = new javax.swing.JLabel();
        txtQtyInBundle = new javax.swing.JTextField();
        txtNoOfBundle = new javax.swing.JTextField();
        txtRowNo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtRackNo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtDiscripton = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblValidation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(19, 15, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Suplier ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Suplier Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 20, -1));

        txtSupId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSupId.setForeground(new java.awt.Color(0, 0, 0));
        txtSupId.setEnabled(false);
        txtSupId.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtSupId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupIdActionPerformed(evt);
            }
        });
        txtSupId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupIdKeyPressed(evt);
            }
        });
        jPanel1.add(txtSupId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, 350, -1));

        txtSupName.setBackground(new java.awt.Color(19, 15, 64));
        txtSupName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSupName.setForeground(new java.awt.Color(255, 255, 255));
        txtSupName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(186, 220, 88)));
        txtSupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 350, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 21, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, 20, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, 20, -1));

        txtSuoContact.setBackground(new java.awt.Color(19, 15, 64));
        txtSuoContact.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSuoContact.setForeground(new java.awt.Color(255, 255, 255));
        txtSuoContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(186, 220, 88)));
        txtSuoContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuoContactActionPerformed(evt);
            }
        });
        txtSuoContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSuoContactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuoContactKeyReleased(evt);
            }
        });
        jPanel1.add(txtSuoContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 350, -1));

        txtSupAddress.setBackground(new java.awt.Color(19, 15, 64));
        txtSupAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSupAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtSupAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(186, 220, 88)));
        txtSupAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtSupAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 350, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Barcode");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtItemId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtItemId.setEnabled(false);
        txtItemId.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 180, -1));

        txtBarcodeId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBarcodeId.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBarcodeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtBarcodeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 290, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qty in Bundle");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("product / publisher name");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Author Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        txtAuthorName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAuthorName.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtAuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 350, -1));

        txtPname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPname.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnameActionPerformed(evt);
            }
        });
        txtPname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 350, -1));

        txtQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQty.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 180, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        buttonGroup1.add(rSchoolStationery);
        rSchoolStationery.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSchoolStationery.setForeground(new java.awt.Color(255, 255, 255));
        rSchoolStationery.setText("School Stationery");
        rSchoolStationery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSchoolStationeryMouseClicked(evt);
            }
        });
        jPanel1.add(rSchoolStationery, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        buttonGroup1.add(rOthers);
        rOthers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rOthers.setForeground(new java.awt.Color(255, 255, 255));
        rOthers.setText("Others");
        rOthers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rOthersMouseClicked(evt);
            }
        });
        jPanel1.add(rOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jButton4.setBackground(new java.awt.Color(52, 73, 94));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("ADDED");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 830, 570, 50));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Total");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, -1, -1));

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 750, 250, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Description");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtUnitPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUnitPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 180, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("selling Price");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtBuyingPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuyingPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBuyingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuyingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 180, -1));

        buyinPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buyinPrice.setForeground(new java.awt.Color(255, 255, 255));
        buyinPrice.setText("Buying Price");
        jPanel1.add(buyinPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 120, -1));

        txtQtyInBundle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQtyInBundle.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtQtyInBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyInBundleActionPerformed(evt);
            }
        });
        jPanel1.add(txtQtyInBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 100, -1));

        txtNoOfBundle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtNoOfBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfBundleActionPerformed(evt);
            }
        });
        txtNoOfBundle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoOfBundleKeyPressed(evt);
            }
        });
        jPanel1.add(txtNoOfBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 100, 30));

        txtRowNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRowNo.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRowNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRowNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRowNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 100, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("row No");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("rack No");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        txtRackNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRackNo.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRackNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRackNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRackNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 100, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Status");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("No of Bundle");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Total Qty");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        txtDiscripton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDiscripton.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDiscripton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscriptonActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiscripton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 350, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Item ID");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(199, 236, 238));
        jLabel37.setText("Suplier Detail");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(199, 236, 238));
        jLabel38.setText("Item Detail");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(199, 236, 238));
        jSeparator1.setForeground(new java.awt.Color(199, 236, 238));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 740, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 10, 440));

        lblValidation.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 340, 20));

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupIdActionPerformed
        txtSupName.requestFocus();
    }//GEN-LAST:event_txtSupIdActionPerformed

    private void txtSupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupNameActionPerformed
        txtSupAddress.requestFocus();
    }//GEN-LAST:event_txtSupNameActionPerformed

    private void txtSuoContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuoContactActionPerformed
        txtBarcodeId.requestFocus();
    }//GEN-LAST:event_txtSuoContactActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
        txtBarcodeId.requestFocus();
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void txtBarcodeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeIdActionPerformed
        txtDiscripton.requestFocus();
    }//GEN-LAST:event_txtBarcodeIdActionPerformed

    private void txtAuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorNameActionPerformed
        txtRackNo.requestFocus();
    }//GEN-LAST:event_txtAuthorNameActionPerformed

    private void txtPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnameActionPerformed
        txtAuthorName.requestFocus();
    }//GEN-LAST:event_txtPnameActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        txtUnitPrice.requestFocus();
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        txtPname.requestFocus();
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtBuyingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingPriceActionPerformed
        int qty = Integer.parseInt(txtQty.getText());
        double netTotal = Double.parseDouble(txtBuyingPrice.getText());

        double total = qty * netTotal;
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtBuyingPriceActionPerformed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed

    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtQtyInBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyInBundleActionPerformed
        txtNoOfBundle.requestFocus();
    }//GEN-LAST:event_txtQtyInBundleActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased

    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed

    }//GEN-LAST:event_txtTotalKeyPressed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtNoOfBundleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfBundleKeyPressed

    }//GEN-LAST:event_txtNoOfBundleKeyPressed

    private void txtRowNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRowNoActionPerformed
        txtQtyInBundle.requestFocus();;
    }//GEN-LAST:event_txtRowNoActionPerformed

    private void txtRackNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRackNoActionPerformed
        txtRowNo.requestFocus();
    }//GEN-LAST:event_txtRackNoActionPerformed

    private void txtSupIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupIdKeyPressed

    }//GEN-LAST:event_txtSupIdKeyPressed

    private void txtSupAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupAddressActionPerformed
        txtSuoContact.requestFocus();
    }//GEN-LAST:event_txtSupAddressActionPerformed

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped


    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtNoOfBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfBundleActionPerformed
        int noOfBundle = Integer.parseInt(txtNoOfBundle.getText());
        int qtyInBox = Integer.parseInt(txtQtyInBundle.getText());
        int total = noOfBundle * qtyInBox;
        txtQty.setText(String.valueOf(total));

        txtBuyingPrice.requestFocus();
    }//GEN-LAST:event_txtNoOfBundleActionPerformed

    private void rSchoolStationeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSchoolStationeryMouseClicked
        if (rSchoolStationery.isSelected()) {
            txtAuthorName.setText("NULL");
        }
    }//GEN-LAST:event_rSchoolStationeryMouseClicked

    private void txtDiscriptonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscriptonActionPerformed
        txtUnitPrice.requestFocus();
    }//GEN-LAST:event_txtDiscriptonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            //        try {
            String suplierId = txtSupId.getText();
            String supName = txtSupName.getText();
            String supAddress = txtSupAddress.getText();
            int contact = Integer.parseInt(txtSuoContact.getText());
            String itemId = txtItemId.getText();
            String description = txtDiscripton.getText();
            String status = getStatus();
            int totalQty = Integer.parseInt(txtQty.getText());
            String product = txtPname.getText();
            String author = txtAuthorName.getText();
            int rackNo = Integer.parseInt(txtRackNo.getText());
            int rowNo = Integer.parseInt(txtRowNo.getText());
            String barcode = txtBarcodeId.getText();
            double unitPrice = Double.parseDouble(txtUnitPrice.getText());
            double fulltotal = Double.parseDouble(txtTotal.getText());

            Object isSaved = new ItemController().addedNewItems(new Items(itemId, description, rackNo, rowNo, totalQty, unitPrice, status, product, author, barcode),
                    new Supliers(suplierId, supName, supAddress, contact),
                    fulltotal
            );
            if (isSaved != null) {
                JOptionPane.showMessageDialog(this, "Saved");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddsupandItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddsupandItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSuoContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuoContactKeyPressed

    }//GEN-LAST:event_txtSuoContactKeyPressed

    private void txtSuoContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuoContactKeyReleased
        try {
            int i = Integer.parseInt(txtSuoContact.getText());
            jLabel1.setText("");
        } catch (NumberFormatException num) {
            jLabel1.setText("Invalid number");
        }
    }//GEN-LAST:event_txtSuoContactKeyReleased

    private void rOthersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rOthersMouseClicked
        if (rOthers.isSelected()) {
            txtAuthorName.setText("");
        }
    }//GEN-LAST:event_rOthersMouseClicked

    private void txtPnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPnameKeyReleased
        int i = txtPname.getCaretPosition();
        txtPname.setText(txtPname.getText().toUpperCase());
        txtPname.setCaretPosition(i);
    }//GEN-LAST:event_txtPnameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddsupandItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddsupandItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddsupandItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddsupandItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddsupandItem().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddsupandItem.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AddsupandItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel buyinPrice;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblValidation;
    private javax.swing.JRadioButton rOthers;
    private javax.swing.JRadioButton rSchoolStationery;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBarcodeId;
    private javax.swing.JTextField txtBuyingPrice;
    private javax.swing.JTextField txtDiscripton;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtNoOfBundle;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQtyInBundle;
    private javax.swing.JTextField txtRackNo;
    private javax.swing.JTextField txtRowNo;
    private javax.swing.JTextField txtSuoContact;
    private javax.swing.JTextField txtSupAddress;
    private javax.swing.JTextField txtSupId;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private String getStatus() {
        String status = "";
        if (rSchoolStationery.isSelected()) {
            status = "staioney";

        } else if (rOthers.isSelected()) {
            status = "Others";

        }
        return status;
    }

    private void loadSuplierId() throws ClassNotFoundException, SQLException {
        String id = new SuplierController().getLastId();
        if (id == null) {
            txtSupId.setText("S0001");
        } else {
            String split[] = id.split("S");

            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                txtSupId.setText("S000" + num);
            } else if (num < 100) {
                txtSupId.setText("S00" + num);
            } else if (num < 1000) {
                txtSupId.setText("S0" + num);
            } else {
                txtSupId.setText("S" + num);
            }

        }
    }

    private void loadItemId() throws ClassNotFoundException, SQLException {
        String id = new ItemController().getLastId();
        if (id == null) {
            txtItemId.setText("T0001");
        } else {
            String split[] = id.split("T");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                txtItemId.setText("T000" + num);
            } else if (num < 100) {
                txtItemId.setText("T00" + num);
            } else if (num < 1000) {
                txtItemId.setText("T0" + num);
            } else {
                txtItemId.setText("T" + num);
            }
        }
    }
}
