/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.Timer;
import lk.ijse.controller.LoginController;
import static lk.ijse.view.LoginMain.txtPassword;

/**
 *
 * @author kushantha
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        try {
            initComponents();
            homePanel1.setVisible(true);
            settingPanel.setVisible(false);
            reportPanel.setVisible(false);
            ItemPanel.setVisible(false);
            cusMangePanel.setVisible(false);
            settingPanel.setVisible(false);
            billPanel.setVisible(false);
            ordersPanel.setVisible(false);
            suplierPanel.setVisible(false);
            logoutPanel.setVisible(false);
            showTime();
            showDate();

            Home customer = new Home();
            jPanel3.add(customer);
//        Toolkit tool = Toolkit.getDefaultToolkit();
//        Dimension dm = new Dimension(tool.getScreenSize());
//        int height = (int) dm.getHeight();
//        int weight = (int) dm.getWidth();
//        setSize(weight,height);
//        setLocation(weight /2 - getWidth() / 2, height /2 - getHeight() /2);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPanel = new javax.swing.JPanel();
        settingPanel = new javax.swing.JPanel();
        ordersPanel = new javax.swing.JPanel();
        btnOrders = new javax.swing.JButton();
        billPanel = new javax.swing.JPanel();
        homePanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        btnPayBill = new javax.swing.JButton();
        cusMangePanel = new javax.swing.JPanel();
        btnManageCustomer = new javax.swing.JButton();
        ItemPanel = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        btnManageItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        suplierPanel = new javax.swing.JPanel();
        btnSupliers = new javax.swing.JButton();
        logoutPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblUsername = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();
        logoutPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menulbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        softNamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bookshop Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1290, 960));
        setSize(new java.awt.Dimension(1290, 960));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanel.setBackground(new java.awt.Color(0, 0, 102));
        btnPanel.setVerifyInputWhenFocusTarget(false);
        btnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(settingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 415, 10, 40));

        ordersPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(ordersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 475, 10, 40));

        btnOrders.setBackground(new java.awt.Color(0, 0, 102));
        btnOrders.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_add_shopping_cart_30px.png"))); // NOI18N
        btnOrders.setText("Make Orders");
        btnOrders.setActionCommand("Setting");
        btnOrders.setAlignmentY(0.0F);
        btnOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdersMouseEntered(evt);
            }
        });
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        btnPanel.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 320, 50));

        billPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
        billPanel.setLayout(billPanelLayout);
        billPanelLayout.setHorizontalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        billPanelLayout.setVerticalGroup(
            billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(billPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 355, 10, 40));

        homePanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout homePanel1Layout = new javax.swing.GroupLayout(homePanel1);
        homePanel1.setLayout(homePanel1Layout);
        homePanel1Layout.setHorizontalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        homePanel1Layout.setVerticalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(homePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 115, 10, 40));

        btnHome.setBackground(new java.awt.Color(0, 0, 102));
        btnHome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_home_32px.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setMaximumSize(new java.awt.Dimension(219, 66));
        btnHome.setMinimumSize(new java.awt.Dimension(219, 66));
        btnHome.setPreferredSize(new java.awt.Dimension(219, 66));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        btnPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 50));

        reportPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(reportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 175, -1, 40));

        btnPayBill.setBackground(new java.awt.Color(0, 0, 102));
        btnPayBill.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPayBill.setForeground(new java.awt.Color(255, 255, 255));
        btnPayBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_check_30px.png"))); // NOI18N
        btnPayBill.setText("Pay Bill");
        btnPayBill.setAlignmentY(0.0F);
        btnPayBill.setMaximumSize(new java.awt.Dimension(219, 66));
        btnPayBill.setMinimumSize(new java.awt.Dimension(219, 66));
        btnPayBill.setPreferredSize(new java.awt.Dimension(219, 66));
        btnPayBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPayBillMouseEntered(evt);
            }
        });
        btnPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillActionPerformed(evt);
            }
        });
        btnPanel.add(btnPayBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 320, 50));

        cusMangePanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout cusMangePanelLayout = new javax.swing.GroupLayout(cusMangePanel);
        cusMangePanel.setLayout(cusMangePanelLayout);
        cusMangePanelLayout.setHorizontalGroup(
            cusMangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        cusMangePanelLayout.setVerticalGroup(
            cusMangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(cusMangePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 295, -1, -1));

        btnManageCustomer.setBackground(new java.awt.Color(0, 0, 102));
        btnManageCustomer.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnManageCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_user_groups_50px.png"))); // NOI18N
        btnManageCustomer.setText("Manage Customer");
        btnManageCustomer.setAlignmentY(0.0F);
        btnManageCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageCustomerMouseEntered(evt);
            }
        });
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });
        btnPanel.add(btnManageCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, 50));

        ItemPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(ItemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 235, -1, -1));

        btnReport.setBackground(new java.awt.Color(0, 0, 102));
        btnReport.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_graph_report_32px.png"))); // NOI18N
        btnReport.setText("Reports");
        btnReport.setAlignmentY(0.0F);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        btnPanel.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 320, 50));

        btnManageItem.setBackground(new java.awt.Color(0, 0, 102));
        btnManageItem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnManageItem.setForeground(new java.awt.Color(255, 255, 255));
        btnManageItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_stationery_50px.png"))); // NOI18N
        btnManageItem.setText("Manage Items");
        btnManageItem.setAlignmentY(0.0F);
        btnManageItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageItemMouseEntered(evt);
            }
        });
        btnManageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageItemActionPerformed(evt);
            }
        });
        btnPanel.add(btnManageItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_menu_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        btnPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 30));

        btnSetting.setBackground(new java.awt.Color(0, 0, 102));
        btnSetting.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_settings_50px_2.png"))); // NOI18N
        btnSetting.setText(" Setting");
        btnSetting.setActionCommand("Setting");
        btnSetting.setAlignmentY(0.0F);
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
        });
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        btnPanel.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 50));

        suplierPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout suplierPanelLayout = new javax.swing.GroupLayout(suplierPanel);
        suplierPanel.setLayout(suplierPanelLayout);
        suplierPanelLayout.setHorizontalGroup(
            suplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        suplierPanelLayout.setVerticalGroup(
            suplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(suplierPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 535, 10, 40));

        btnSupliers.setBackground(new java.awt.Color(0, 0, 102));
        btnSupliers.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSupliers.setForeground(new java.awt.Color(255, 255, 255));
        btnSupliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_van_48px.png"))); // NOI18N
        btnSupliers.setText("Add Supliers & item");
        btnSupliers.setActionCommand("Setting");
        btnSupliers.setAlignmentY(0.0F);
        btnSupliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupliersMouseEntered(evt);
            }
        });
        btnSupliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupliersActionPerformed(evt);
            }
        });
        btnPanel.add(btnSupliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 320, 50));

        logoutPanel.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 595, 10, 40));

        btnLogout.setBackground(new java.awt.Color(0, 0, 102));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_logout_rounded_up_26px.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setActionCommand("Setting");
        btnLogout.setAlignmentY(0.0F);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 320, 50));
        btnPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 340, 10));

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        btnPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 727, 130, 20));

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Welcome ");
        btnPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 713, -1, 50));

        btnLogout1.setBackground(new java.awt.Color(0, 0, 102));
        btnLogout1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_logout_rounded_up_26px.png"))); // NOI18N
        btnLogout1.setText("Logout");
        btnLogout1.setActionCommand("Setting");
        btnLogout1.setAlignmentY(0.0F);
        btnLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogout1MouseEntered(evt);
            }
        });
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        btnPanel.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 320, 50));

        logoutPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout logoutPanel1Layout = new javax.swing.GroupLayout(logoutPanel1);
        logoutPanel1.setLayout(logoutPanel1Layout);
        logoutPanel1Layout.setHorizontalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        logoutPanel1Layout.setVerticalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnPanel.add(logoutPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 595, 10, 40));

        getContentPane().add(btnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 335, 770));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menulbl.setBackground(new java.awt.Color(0, 0, 0));
        menulbl.setForeground(new java.awt.Color(51, 51, 51));
        menulbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_menu_32px_1.png"))); // NOI18N
        menulbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menulblMouseEntered(evt);
            }
        });
        jPanel2.add(menulbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 0, 960, 710));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1290, -1));

        softNamePanel.setBackground(new java.awt.Color(0, 0, 102));
        softNamePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        softNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/logo1.png"))); // NOI18N
        softNamePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bookshop Management System");
        softNamePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        softNamePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/rectangle.jpg"))); // NOI18N
        softNamePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 990, 100));

        getContentPane().add(softNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 120));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Time");
        jPanel4.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        lblDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date");
        jPanel4.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 830, 960, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed

    }//GEN-LAST:event_btnPayBillActionPerformed
    private void showDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd,MMM YYYY");
        lblDate.setText(sdf.format(date));
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss");
                lblTime.setText(sd.format(d));
            }
        }).start();
    }
    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        try {
            OrderPanel order = new OrderPanel();
            jPanel3.removeAll();
            jPanel3.repaint();
            jPanel3.revalidate();

//            OrderPanel.txtUname.setText(this.lblUsername.getText());
            String foundData = new LoginController().searchUserId(this.lblUsername.getText());
            OrderPanel.lblOrderId2.setText(foundData);

            jPanel3.add(order);
            jPanel3.repaint();
            jPanel3.revalidate();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        homePanel1.setVisible(true);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        settingPanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);

    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased

    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        try {
            Home customer = new Home();
            jPanel3.removeAll();
            jPanel3.repaint();
            jPanel3.revalidate();

            jPanel3.add(customer);
            jPanel3.repaint();
            jPanel3.revalidate();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        homePanel1.setVisible(false);
        reportPanel.setVisible(true);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        settingPanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnManageItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageItemMouseEntered
        reportPanel.setVisible(false);
        ItemPanel.setVisible(true);
        homePanel1.setVisible(false);
        settingPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnManageItemMouseEntered

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked

    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnManageCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCustomerMouseEntered
        cusMangePanel.setVisible(true);
        homePanel1.setVisible(false);
        settingPanel.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        settingPanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnManageCustomerMouseEntered

    private void btnPayBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayBillMouseEntered
        billPanel.setVisible(true);
        homePanel1.setVisible(false);
        settingPanel.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        settingPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);

    }//GEN-LAST:event_btnPayBillMouseEntered

    private void btnOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdersMouseEntered
        settingPanel.setVisible(false);
        homePanel1.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(true);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnOrdersMouseEntered

    private void menulblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulblMouseEntered

    }//GEN-LAST:event_menulblMouseEntered

    private void menulblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulblMouseClicked
        btnPanel.setVisible(true);
        menulbl.setVisible(false);
    }//GEN-LAST:event_menulblMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        btnPanel.setVisible(false);
        menulbl.setVisible(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void btnManageCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCustomerMouseClicked

    }//GEN-LAST:event_btnManageCustomerMouseClicked

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        ManageCustomer customer = new ManageCustomer();
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(customer);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnManageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageItemActionPerformed
        String username = LoginMain.txtUserName.getText();
        String password = new String(LoginMain.txtPassword.getPassword());

        try {
            String checkRole = new LoginController().checkRole(username, password);

            if (checkRole.equals("Owner")) {

                ManageItem item = new ManageItem();
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(item);
                jPanel3.repaint();
                jPanel3.revalidate();

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManageItemActionPerformed

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        settingPanel.setVisible(true);
        homePanel1.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed

    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnSupliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupliersMouseEntered
        settingPanel.setVisible(false);
        homePanel1.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(true);
        logoutPanel.setVisible(false);
    }//GEN-LAST:event_btnSupliersMouseEntered

    private void btnSupliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupliersActionPerformed
        logoutPanel.setVisible(false);
        settingPanel.setVisible(false);
        homePanel1.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(true);
    }//GEN-LAST:event_btnSupliersActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        logoutPanel.setVisible(true);
        settingPanel.setVisible(false);
        homePanel1.setVisible(false);
        reportPanel.setVisible(false);
        ItemPanel.setVisible(false);
        cusMangePanel.setVisible(false);
        billPanel.setVisible(false);
        ordersPanel.setVisible(false);
        suplierPanel.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginMain main = new LoginMain();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSupliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupliersMouseClicked
        String username = LoginMain.txtUserName.getText();
        String password = new String(LoginMain.txtPassword.getPassword());

        try {
            String checkRole = new LoginController().checkRole(username, password);

            if (checkRole.equals("Owner")) {

                ManageSupliers suplier = new ManageSupliers();
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(suplier);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSupliersMouseClicked

    private void btnPayBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayBillMouseClicked
        try {
            PayBill bill = new PayBill();
            PayBill.userName.setText(this.lblUsername.getText());
            bill.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPayBillMouseClicked

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        String username = LoginMain.txtUserName.getText();
        String password = new String(LoginMain.txtPassword.getPassword());

        try {
            String checkRole = new LoginController().checkRole(username, password);

            if (checkRole.equals("Owner")) {
                ManageSetting setting = new ManageSetting();
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(setting);
                jPanel3.repaint();
                jPanel3.revalidate();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        ManageReport report = new ManageReport();

        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(report);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnLogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1MouseEntered

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JPanel billPanel;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageItem;
    private javax.swing.JButton btnOrders;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JButton btnReport;
    public static javax.swing.JButton btnSetting;
    private javax.swing.JButton btnSupliers;
    private javax.swing.JPanel cusMangePanel;
    private javax.swing.JPanel homePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    public static javax.swing.JLabel lblUsername;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel logoutPanel1;
    private javax.swing.JLabel menulbl;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel softNamePanel;
    private javax.swing.JPanel suplierPanel;
    // End of variables declaration//GEN-END:variables
}
