/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.controller.CustomerController;
import lk.ijse.controller.ItemController;
import lk.ijse.controller.SuplierController;
import lk.ijse.model.Items;
import lk.ijse.model.Supliers;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kushantha
 */
public class ManageItem extends javax.swing.JPanel {

    /**
     * Creates new form MnageItem
     */
    public ManageItem() throws ClassNotFoundException, SQLException {
        initComponents();
        loadAllSupId();
        AutoCompleteDecorator.decorate(comboSupId);
        getLastItemId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAuthorName = new javax.swing.JTextField();
        txtItemId = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtBarcodeId = new javax.swing.JTextField();
        txtNoOfBundle = new javax.swing.JTextField();
        txtTotalQty = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        barcide = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        rOthers = new javax.swing.JRadioButton();
        rStationery = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtRackNo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRowNo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        comboSupId = new javax.swing.JComboBox<>();
        txtBuyingPrice = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtQtyInBundle1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Item ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Qty in Bundle");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Author Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("No of Bundle");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total Qty");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Product / Publisher");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText(":");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 20, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText(":");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 20, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText(":");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 20, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText(":");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 20, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText(":");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 20, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText(":");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 20, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText(":");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 20, -1));

        txtAuthorName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAuthorName.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtAuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorNameActionPerformed(evt);
            }
        });
        add(txtAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 535, 229, -1));

        txtItemId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtItemId.setEnabled(false);
        txtItemId.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 135, 229, -1));

        txtDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescription.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyReleased(evt);
            }
        });
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 85, 229, -1));

        txtBarcodeId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBarcodeId.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBarcodeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeIdActionPerformed(evt);
            }
        });
        add(txtBarcodeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 235, 229, -1));

        txtNoOfBundle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNoOfBundle.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtNoOfBundle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfBundleActionPerformed(evt);
            }
        });
        txtNoOfBundle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfBundleKeyReleased(evt);
            }
        });
        add(txtNoOfBundle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 335, 229, -1));

        txtTotalQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotalQty.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtTotalQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalQtyActionPerformed(evt);
            }
        });
        add(txtTotalQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 385, 229, -1));

        txtUnitPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUnitPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 435, 229, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Manage Items");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        btnSearch.setBackground(new java.awt.Color(204, 0, 204));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_search_32px.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 120, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/school-stationery-png-.png"))); // NOI18N
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 390, 240));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Unit Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText(":");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 20, -1));

        txtProductName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtProductName.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });
        txtProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductNameKeyReleased(evt);
            }
        });
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 229, -1));

        barcide.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        barcide.setForeground(new java.awt.Color(0, 0, 0));
        barcide.setText("Barcode");
        add(barcide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText(":");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 20, -1));

        addbtn.setBackground(new java.awt.Color(153, 0, 0));
        addbtn.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_add_new_52px_1.png"))); // NOI18N
        addbtn.setText("Add ");
        addbtn.setIconTextGap(1);
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 130, 50));

        buttonGroup1.add(rOthers);
        rOthers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rOthers.setText("Others");
        rOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOthersActionPerformed(evt);
            }
        });
        add(rOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 485, -1, -1));

        buttonGroup1.add(rStationery);
        rStationery.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rStationery.setText("Stationery");
        rStationery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rStationeryMouseClicked(evt);
            }
        });
        add(rStationery, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 485, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText(":");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 20, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Status");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        txtRackNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRackNo.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRackNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRackNoActionPerformed(evt);
            }
        });
        add(txtRackNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 229, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText(":");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 20, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Rack no");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        txtRowNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRowNo.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRowNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRowNoActionPerformed(evt);
            }
        });
        add(txtRowNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 229, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText(":");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 20, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Added Qty");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 635, 230, -1));

        lblName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 30));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Total");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 100, 30));

        comboSupId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboSupId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Suplier ID" }));
        comboSupId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSupIdItemStateChanged(evt);
            }
        });
        comboSupId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSupIdActionPerformed(evt);
            }
        });
        add(comboSupId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 185, 230, -1));

        txtBuyingPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuyingPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBuyingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingPriceActionPerformed(evt);
            }
        });
        txtBuyingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuyingPriceKeyReleased(evt);
            }
        });
        add(txtBuyingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 585, 230, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Buying Price");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 130, 30));

        txtQtyInBundle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQtyInBundle1.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtQtyInBundle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyInBundle1ActionPerformed(evt);
            }
        });
        add(txtQtyInBundle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 285, 229, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Suplier ID");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnSearch1.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/pictures/icons8_add_new_60px.png"))); // NOI18N
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch1MouseClicked(evt);
            }
        });
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 70, 70));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Row No");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/itembaskground1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorNameActionPerformed
        txtBuyingPrice.requestFocus();
    }//GEN-LAST:event_txtAuthorNameActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        comboSupId.requestFocus();
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtBarcodeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeIdActionPerformed
        txtQtyInBundle1.requestFocus();
    }//GEN-LAST:event_txtBarcodeIdActionPerformed

    private void txtNoOfBundleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfBundleActionPerformed
        txtUnitPrice.requestFocus();
    }//GEN-LAST:event_txtNoOfBundleActionPerformed

    private void txtTotalQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalQtyActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        txtProductName.requestFocus();
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        txtRackNo.requestFocus();
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed


    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtRackNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRackNoActionPerformed
        txtRowNo.requestFocus();
    }//GEN-LAST:event_txtRackNoActionPerformed

    private void txtRowNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRowNoActionPerformed

    }//GEN-LAST:event_txtRowNoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        try {
            ItemSearch item = new ItemSearch();
            item.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchMouseClicked
    private void clearText() {

        txtDescription.setText("");
        txtBarcodeId.setText("");
        txtNoOfBundle.setText("");
        txtTotalQty.setText("");
        txtUnitPrice.setText("");
        rStationery.setSelected(false);
        rOthers.setSelected(false);
        txtProductName.setText("");
        txtAuthorName.setText("");
        txtRackNo.setText("");
        txtRowNo.setText("");
        txtBuyingPrice.setText("");
        txtTotal.setText("");
        txtQtyInBundle1.setText("");
        
    }
    private void comboSupIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSupIdActionPerformed
        txtBarcodeId.requestFocus();
    }//GEN-LAST:event_comboSupIdActionPerformed

    private void txtBuyingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingPriceActionPerformed
        txtProductName.requestFocus();
    }//GEN-LAST:event_txtBuyingPriceActionPerformed

    private void comboSupIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSupIdItemStateChanged
        try {
            String supId = (String) comboSupId.getSelectedItem();
            Supliers suplier = new SuplierController().getSupliers(supId);
            lblName.setText(suplier.getSupName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboSupIdItemStateChanged

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            String supId = String.valueOf(comboSupId.getSelectedItem());
            String itemId = txtItemId.getText();
            String description = txtDescription.getText();
            int qty = Integer.parseInt(txtTotalQty.getText());
            double uniPrice = Double.parseDouble(txtUnitPrice.getText());
            String status = getStatus();
            String pname = txtProductName.getText();
            String author = txtAuthorName.getText();
            int rackNo = Integer.parseInt(txtRackNo.getText());
            int rowNo = Integer.parseInt(txtRowNo.getText());
            double total = Double.parseDouble(txtTotal.getText());
            String barcode = txtBarcodeId.getText();
            
            Object isSaved = new ItemController().addItems(new Items(itemId, description, rackNo, rowNo, qty,
                    uniPrice, status, pname, author,barcode), supId, total);
            if (isSaved != null) {
                JOptionPane.showMessageDialog(null, "Saved Item");
                clearText();
                getLastItemId();
            } else {
                JOptionPane.showMessageDialog(null, "Check again");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void rStationeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rStationeryMouseClicked
        if (rStationery.isSelected()) {
            txtAuthorName.setText("NULL");
        } else if (rOthers.isSelected()) {
            txtAuthorName.setText("");
        }
    }//GEN-LAST:event_rStationeryMouseClicked

    private void rOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rOthersActionPerformed

    private void txtBuyingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuyingPriceKeyReleased
        try {
            int qty = Integer.parseInt(txtTotalQty.getText());
            double buyingPrice = Double.parseDouble(txtBuyingPrice.getText());
            double total = qty * buyingPrice;
            txtTotal.setText(Double.toString(total));
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_txtBuyingPriceKeyReleased

    private void txtNoOfBundleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfBundleKeyReleased
        try {
            int qtyInBundle = Integer.parseInt(txtQtyInBundle1.getText());
            int noOfBundle = Integer.parseInt(txtNoOfBundle.getText());
            int total = noOfBundle * qtyInBundle;
            txtTotalQty.setText(Integer.toString(total));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_txtNoOfBundleKeyReleased

    private void txtQtyInBundle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyInBundle1ActionPerformed
        txtNoOfBundle.requestFocus();
    }//GEN-LAST:event_txtQtyInBundle1ActionPerformed

    private void btnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MouseClicked

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        AddedQty qty = new AddedQty();
        qty.setVisible(true);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtDescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyReleased
        int i = txtDescription.getCaretPosition();
        txtDescription.setText(txtDescription.getText().toUpperCase());
        txtDescription.setCaretPosition(i);
    }//GEN-LAST:event_txtDescriptionKeyReleased

    private void txtProductNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductNameKeyReleased
        int i = txtProductName.getCaretPosition();
        txtProductName.setText(txtProductName.getText().toUpperCase());
        txtProductName.setCaretPosition(i);
    }//GEN-LAST:event_txtProductNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel barcide;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboSupId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblName;
    private javax.swing.JRadioButton rOthers;
    private javax.swing.JRadioButton rStationery;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBarcodeId;
    private javax.swing.JTextField txtBuyingPrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtNoOfBundle;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQtyInBundle1;
    private javax.swing.JTextField txtRackNo;
    private javax.swing.JTextField txtRowNo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalQty;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void loadAllSupId() throws ClassNotFoundException, SQLException {
        for (String temp : new SuplierController().getAllId()) {
            comboSupId.addItem(temp);
        }
    }

    private void getLastItemId() throws ClassNotFoundException, SQLException {
        String id = new ItemController().getLastId();
        if (id == null) {
            txtItemId.setText("T0001");
        } else {
            String split[] = id.split("T");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                txtItemId.setText("T000" + num);
            } else if (num < 100) {
                txtItemId.setText("T00" + num);
            } else if (num < 1000) {
                txtItemId.setText("T0" + num);
            } else {
                txtItemId.setText("T" + num);
            }
        }

    }

    private String getStatus() {
        String status = "";
        if (rStationery.isSelected()) {
            status = "Stationery";

        } else if (rOthers.isSelected()) {
            status = "Others";
        }
        return status;
    }
}
