/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.bookshop.DB.DBConnection;
import lk.ijse.controller.CustomerController;
import lk.ijse.model.Customer;

/**
 *
 * @author kushantha
 */
public class ManageCustomer extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomer
     */
    public ManageCustomer() {
        try {
            initComponents();
            txtCustId.setBackground(new Color(0, 0, 0, 64));
            txtCustIdCard.setBackground(new Color(0, 0, 0, 64));
            txtCustomerName.setBackground(new Color(0, 0, 0, 64));
            txtCustomerContact.setBackground(new Color(0, 0, 0, 64));
            txtAddress1.setBackground(new Color(0, 0, 0, 64));
            txtAddress2.setBackground(new Color(0, 0, 0, 64));
            txtCustCity.setBackground(new Color(0, 0, 0, 64));
            txtRegfee.setBackground(new Color(0, 0, 0, 64));

            loadCustomerId();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCustIdCard = new javax.swing.JTextField();
        txtCustId = new javax.swing.JTextField();
        txtCustomerContact = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCustCity = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnCustAdd = new javax.swing.JButton();
        btnCustSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtRegfee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(44, 62, 80));
        setPreferredSize(new java.awt.Dimension(960, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Customer ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 62, 80));
        jLabel3.setText("Address line 1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Customer name ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Nationality ID no");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Contact");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("City");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Addres line 2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText(":");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText(":");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 200, 21, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText(":");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 20, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 62, 80));
        jLabel12.setText(":");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 20, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(44, 62, 80));
        jLabel13.setText(":");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(44, 62, 80));
        jLabel14.setText(":");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(44, 62, 80));
        jLabel15.setText(":");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 450, -1, -1));

        txtCustIdCard.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustIdCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIdCardActionPerformed(evt);
            }
        });
        add(txtCustIdCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 229, -1));

        txtCustId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIdActionPerformed(evt);
            }
        });
        add(txtCustId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 229, -1));

        txtCustomerContact.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustomerContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerContactActionPerformed(evt);
            }
        });
        txtCustomerContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerContactKeyReleased(evt);
            }
        });
        add(txtCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 229, -1));

        txtAddress1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });
        add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 229, -1));

        txtAddress2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress2ActionPerformed(evt);
            }
        });
        add(txtAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 229, -1));

        txtCustCity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustCityActionPerformed(evt);
            }
        });
        add(txtCustCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 229, -1));

        txtCustomerName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyReleased(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 229, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/mini-publishing-girl-books.png"))); // NOI18N
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 290, 370));

        btnCustAdd.setBackground(new java.awt.Color(204, 0, 204));
        btnCustAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCustAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnCustAdd.setText("ADD");
        btnCustAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustAddActionPerformed(evt);
            }
        });
        add(btnCustAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 120, 40));

        btnCustSearch.setBackground(new java.awt.Color(204, 0, 204));
        btnCustSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCustSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnCustSearch.setText("Search");
        btnCustSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustSearchMouseClicked(evt);
            }
        });
        btnCustSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustSearchActionPerformed(evt);
            }
        });
        add(btnCustSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 120, 40));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Manage Customer");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(44, 62, 80));
        jLabel19.setText("Reg fee");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(44, 62, 80));
        jLabel20.setText(":");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        txtRegfee.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRegfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegfeeActionPerformed(evt);
            }
        });
        add(txtRegfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 229, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/background.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIdActionPerformed

    private void txtCustomerContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerContactActionPerformed
        txtAddress1.requestFocus();

    }//GEN-LAST:event_txtCustomerContactActionPerformed

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        txtAddress2.requestFocus();
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void txtAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress2ActionPerformed
        txtCustCity.requestFocus();
    }//GEN-LAST:event_txtAddress2ActionPerformed

    private void txtCustCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustCityActionPerformed
        txtRegfee.requestFocus();
    }//GEN-LAST:event_txtCustCityActionPerformed

    private void btnCustSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustSearchMouseClicked


    }//GEN-LAST:event_btnCustSearchMouseClicked

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        txtCustIdCard.requestFocus();
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnCustAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustAddActionPerformed

        try {
            String id = txtCustId.getText();
            String name = txtCustomerName.getText();
            String nic = txtCustIdCard.getText();
            String city = txtCustCity.getText();
            String line1 = txtAddress1.getText();
            String line2 = txtAddress2.getText();
            int contact = Integer.parseInt(txtCustomerContact.getText());
            double regfee = Double.parseDouble(txtRegfee.getText());
            double point = 0;
            boolean isSaved = new CustomerController().addedCustomer(new Customer(id, name, nic, city, contact, line1, line2, regfee, point));

            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Saved");
                clear();
                loadCustomerId();

            } else {
                JOptionPane.showMessageDialog(this, "check again");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCustAddActionPerformed
//    public void updateregfee() throws ClassNotFoundException, SQLException{
//            Connection connection = DBConnection.getInstance().getConnection();
//            String sql ="update customer set regfee=? where cust_id = ?; ";
//            PreparedStatement pstm = connection.prepareStatement(sql);
//            pstm.setObject(1, txtRegfee.getText());
//            pstm.setObject(2, txtCustId.getText());
//            pstm.executeUpdate();
//    }
    private void btnCustSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustSearchActionPerformed
        try {
            SearchCustomer search = new SearchCustomer();
            search.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustSearchActionPerformed

    private void txtRegfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegfeeActionPerformed

    private void txtCustIdCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIdCardActionPerformed
        txtCustomerContact.requestFocus();
    }//GEN-LAST:event_txtCustIdCardActionPerformed

    private void txtCustomerContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerContactKeyReleased
        try {
            int i = Integer.parseInt(txtCustomerContact.getText());
            jLabel1.setText("");
        } catch (NumberFormatException num) {
            jLabel1.setText("Invalid number");
        }
    }//GEN-LAST:event_txtCustomerContactKeyReleased

    private void txtCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyReleased
        int i = txtCustomerName.getCaretPosition();
        txtCustomerName.setText(txtCustomerName.getText().toUpperCase());
        txtCustomerName.setCaretPosition(i);
    }//GEN-LAST:event_txtCustomerNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustAdd;
    private javax.swing.JButton btnCustSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCustCity;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtCustIdCard;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtRegfee;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        
        txtCustomerName.setText("");
        txtCustIdCard.setText("");
        txtCustCity.setText("");
        txtAddress1.setText("");
        txtAddress2.setText("");
        txtCustomerContact.setText("");
        txtRegfee.setText("");
    }

    private void loadCustomerId() throws ClassNotFoundException, SQLException {
        String id = new CustomerController().getLastId();
        if (id == null) {
            txtCustId.setText("C0001");
        } else {
            String split[] = id.split("C");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                txtCustId.setText("C000" + num);
            } else if (num < 100) {
                txtCustId.setText("C00" + num);
            } else if (num < 1000) {
                txtCustId.setText("C0" + num);
            } else {
                txtCustId.setText("C" + num);
            }
        }
    }
}
