/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.controller.DiscountController;
import lk.ijse.controller.ItemController;
import lk.ijse.model.CashDiscount;
import lk.ijse.model.DateDiscount;
import lk.ijse.model.Items;

/**
 *
 * @author kushantha
 */
public class ManageSetting extends javax.swing.JPanel {

    /**
     * Creates new form ManageSetting
     */
    public ManageSetting() throws ClassNotFoundException, SQLException {
        initComponents();
        loadProduct();
        loadAllDiscount();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCardDiscount = new javax.swing.JTextField();
        txtDayDiscount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboMonth = new javax.swing.JComboBox<>();
        txtMonthDiscount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtPdiscount = new javax.swing.JTextField();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        comboProduct = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        additonValue1 = new javax.swing.JTextField();
        txtRange1 = new javax.swing.JTextField();
        txtRange2 = new javax.swing.JTextField();
        additionValue2 = new javax.swing.JTextField();
        txtRange3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        txtRD3 = new javax.swing.JTextField();
        txtRD1 = new javax.swing.JTextField();
        txtRD2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(47, 54, 64));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discount  ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("%");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Month");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Discount ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Discount ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        txtCardDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCardDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtCardDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardDiscountActionPerformed(evt);
            }
        });
        add(txtCardDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 275, 120, -1));

        txtDayDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDayDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDayDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayDiscountActionPerformed(evt);
            }
        });
        add(txtDayDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 125, 60, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Discount");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 570, 10));

        comboMonth.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        add(comboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 65, 210, -1));

        txtMonthDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMonthDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtMonthDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthDiscountActionPerformed(evt);
            }
        });
        add(txtMonthDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 125, 60, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("%");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 675, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 960, 10));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 960, 10));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("%");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        txtPdiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPdiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtPdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPdiscountActionPerformed(evt);
            }
        });
        add(txtPdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 455, 60, -1));

        jDateChooser4.setDateFormatString("d-MM-yyyy");
        jDateChooser4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 65, 210, 30));

        comboProduct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select product name" }));
        comboProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProductItemStateChanged(evt);
            }
        });
        add(comboProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 210, -1));

        jButton1.setBackground(new java.awt.Color(34, 112, 147));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 472, 90, 40));

        jButton2.setBackground(new java.awt.Color(34, 112, 147));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Detial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 172, 90, 40));

        jButton3.setBackground(new java.awt.Color(34, 112, 147));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 172, 90, 40));

        jButton4.setBackground(new java.awt.Color(34, 112, 147));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Delete all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 662, 100, 40));

        jButton5.setBackground(new java.awt.Color(34, 112, 147));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 472, 90, 40));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 220));

        additonValue1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        additonValue1.setSelectionColor(new java.awt.Color(0, 0, 204));
        additonValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additonValue1ActionPerformed(evt);
            }
        });
        add(additonValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 140, -1));

        txtRange1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRange1.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRange1ActionPerformed(evt);
            }
        });
        add(txtRange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 140, -1));

        txtRange2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRange2.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRange2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRange2ActionPerformed(evt);
            }
        });
        add(txtRange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 140, -1));

        additionValue2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        additionValue2.setSelectionColor(new java.awt.Color(0, 0, 204));
        additionValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionValue2ActionPerformed(evt);
            }
        });
        add(additionValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 140, -1));

        txtRange3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRange3.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtRange3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRange3ActionPerformed(evt);
            }
        });
        add(txtRange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 140, -1));

        jButton7.setBackground(new java.awt.Color(34, 112, 147));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 292, 90, 40));

        jButton8.setBackground(new java.awt.Color(34, 112, 147));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setText("ADD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 90, 40));

        jButton9.setBackground(new java.awt.Color(34, 112, 147));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setText("ADD");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 612, 90, 40));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 960, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 570, 20));

        jButton10.setBackground(new java.awt.Color(34, 112, 147));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setText("ADD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 664, 90, 40));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("(1000-2000)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("(2000-3000)");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(3000)");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 40, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("-");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 40, -1));

        jButton11.setBackground(new java.awt.Color(34, 112, 147));
        jButton11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton11.setText("ADD");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 172, 90, 40));

        jButton12.setBackground(new java.awt.Color(34, 112, 147));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton12.setText("Detail");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 172, 90, 40));

        txtRD3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(txtRD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 60, 30));

        txtRD1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(txtRD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 60, 30));

        txtRD2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(txtRD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 60, 30));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("%");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("%");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 575, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("%");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 625, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adding discount for the amout ranges");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("adding day discount");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("adding month discount");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("adding card discount");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Adding product discount");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCardDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardDiscountActionPerformed

    private void txtDayDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayDiscountActionPerformed


    }//GEN-LAST:event_txtDayDiscountActionPerformed

    private void txtMonthDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthDiscountActionPerformed

    private void txtPdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPdiscountActionPerformed

    private void comboProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProductItemStateChanged
        try {
            String product = (String) comboProduct.getSelectedItem();
            String item = new ItemController().getProduct(product);
            txtPdiscount.setText(item);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProductItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String pname = (String) comboProduct.getSelectedItem();
            double discount = Double.parseDouble(txtPdiscount.getText());
            boolean updateDiscount = new ItemController().updateDiscount(discount, pname);

            if (updateDiscount) {
                JOptionPane.showMessageDialog(null, "Added Discount");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            String pname = (String) comboProduct.getSelectedItem();

            boolean deleteDiscount = new ItemController().deleteDiscount(pname);
            if (deleteDiscount) {
                JOptionPane.showMessageDialog(null, "discount removed");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            MonthDetail m1 = new MonthDetail();
            m1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void additonValue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additonValue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additonValue1ActionPerformed

    private void txtRange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRange1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRange1ActionPerformed

    private void txtRange2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRange2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRange2ActionPerformed

    private void additionValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additionValue2ActionPerformed

    private void txtRange3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRange3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRange3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        try {
            DateFormat df = new SimpleDateFormat("YYYY-MM-dd");
            String date = (df.format(jDateChooser4.getDate()));
            double discount = Integer.parseInt(txtDayDiscount.getText());
            boolean isAdded = new DiscountController().addedDayDiscout(date, discount);
            
            if(isAdded){
                JOptionPane.showMessageDialog(null, "Saved");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            Detail detail = new Detail();
            detail.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 
        try {
            double discount = Double.parseDouble(txtCardDiscount.getText());
            boolean isSaved = new DiscountController().updateCardDiscount(discount);
            if(isSaved){
                JOptionPane.showMessageDialog(null, "Saved");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            double range1 = Double.parseDouble(txtRange1.getText());
            double discount = Double.parseDouble(txtRD1.getText());
            boolean isAdded = new DiscountController().addedRange1Value(range1,discount);
            if(isAdded){
                JOptionPane.showMessageDialog(null, "Added Discount");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            double range2 = Double.parseDouble(txtRange2.getText());
            double discount = Double.parseDouble(txtRD2.getText());
            
            boolean isAdded = new DiscountController().addedRange1Value2(range2,discount);
            if(isAdded){
                JOptionPane.showMessageDialog(null, "Added Discount");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            double range3 = Double.parseDouble(txtRange3.getText());
            double discount = Double.parseDouble(txtRD3.getText());
            boolean isAdded = new DiscountController().addedRange1Value3(range3,discount);
            if(isAdded){
                JOptionPane.showMessageDialog(null, "Added Discount");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            boolean isDelete = new DiscountController().deleteAll();
            if(isDelete){
                JOptionPane.showMessageDialog(null, "Deleted Discount");
                loadAllDiscount();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String month = (String)comboMonth.getSelectedItem();
            double discount = Integer.parseInt(txtMonthDiscount.getText());
            boolean isAdded = new DiscountController().addedMonthDiscount(month, discount);
            
            if(isAdded){
                 JOptionPane.showMessageDialog(null, "Added Discount");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField additionValue2;
    private javax.swing.JTextField additonValue1;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboProduct;
    private javax.swing.ButtonGroup dateGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtCardDiscount;
    private javax.swing.JTextField txtDayDiscount;
    private javax.swing.JTextField txtMonthDiscount;
    private javax.swing.JTextField txtPdiscount;
    private javax.swing.JTextField txtRD1;
    private javax.swing.JTextField txtRD2;
    private javax.swing.JTextField txtRD3;
    private javax.swing.JTextField txtRange1;
    private javax.swing.JTextField txtRange2;
    private javax.swing.JTextField txtRange3;
    // End of variables declaration//GEN-END:variables

    private void loadProduct() throws ClassNotFoundException, SQLException {
        for (String temp : new DiscountController().getProduct()) {
            comboProduct.addItem(temp);
        }
    }

    private void loadAllDiscount() throws ClassNotFoundException, SQLException {

        String cardDiscount = new DiscountController().getCardDiscount();
        txtCardDiscount.setText(cardDiscount);
        
//        String range1 = new DiscountController().getRange1();
//        txtRange1.setText(range1);
        
        for (CashDiscount disocunt : new DiscountController().getRange1()){
            txtRange1.setText(Double.toString(disocunt.getCash()));
            txtRD1.setText(Double.toString(disocunt.getDiscount()));
        }
        for (CashDiscount disocunt : new DiscountController().getRange2()){
            txtRange2.setText(Double.toString(disocunt.getCash()));
            
            additonValue1.setText(Double.toString(disocunt.getCash()));
            txtRD2.setText(Double.toString(disocunt.getDiscount()));
        }
        for (CashDiscount disocunt : new DiscountController().getRange3()){
            txtRange3.setText(Double.toString(disocunt.getCash()));
            txtRD3.setText(Double.toString(disocunt.getDiscount()));
            additionValue2.setText(Double.toString(disocunt.getCash()));
        }
//        String range2 = new DiscountController().getRange2();
//        additonValue1.setText(range2);
//        txtRange2.setText(range2);
//        
//        String range3 = new DiscountController().getRange3();
//        additionValue2.setText(range3);
//        txtRange3.setText(range3);

    }
}
