/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.controller.CustomerController;
import lk.ijse.controller.ItemController;
import lk.ijse.controller.OrderController;
import lk.ijse.controller.OrderDetailController;
import lk.ijse.model.Customer;
import lk.ijse.model.Items;
import lk.ijse.model.Order;
import lk.ijse.model.OrderDetail;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kushantha
 */
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() throws ClassNotFoundException, SQLException {
        initComponents();
        loadContact();
        AutoCompleteDecorator.decorate(comboCustContact);
        AutoCompleteDecorator.decorate(comboDiscription);
        loadDescription();
        getLastId();
        loadAlOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRomove = new javax.swing.JButton();
        txtQty = new javax.swing.JTextField();
        comboCustContact = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblOrdered = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblorders = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        lblOrderId2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblOrderId = new javax.swing.JLabel();
        lblItemId = new javax.swing.JLabel();
        comboDiscription = new javax.swing.JComboBox<>();
        btnAddToCart1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblItemDetail = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 152, 219));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(0, 0, 0));
        lblCustName.setText("Customer name");
        add(lblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Order detail");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        btnRomove.setBackground(new java.awt.Color(0, 0, 102));
        btnRomove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRomove.setForeground(new java.awt.Color(255, 255, 255));
        btnRomove.setText("Remove");
        btnRomove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomoveActionPerformed(evt);
            }
        });
        add(btnRomove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 160, 50));

        txtQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, 40));

        comboCustContact.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboCustContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCustContactItemStateChanged(evt);
            }
        });
        comboCustContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustContactActionPerformed(evt);
            }
        });
        add(comboCustContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 250, 40));

        tbl1.setBackground(new java.awt.Color(51, 153, 255));
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item", "Qty"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 330, 280));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Customer ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblOrdered.setBackground(new java.awt.Color(0, 0, 153));
        lblOrdered.setForeground(new java.awt.Color(51, 0, 204));
        add(lblOrdered, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 960, 10));

        tblorders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "customer Id", "Date"
            }
        ));
        tblorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblordersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblorders);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 450, 250));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("qty");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lblOrder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(0, 0, 0));
        lblOrder.setText("N/A");
        add(lblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        lblOrderId2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrderId2.setForeground(new java.awt.Color(0, 0, 0));
        lblOrderId2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderId2.setText("UserID");
        lblOrderId2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblOrderId2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblOrderId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 5, 80, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Order Id   :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        btnPlaceOrder.setBackground(new java.awt.Color(0, 0, 102));
        btnPlaceOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 160, 50));

        btnSearch.setBackground(new java.awt.Color(204, 0, 204));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("View Item");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 120, 40));

        lblOrderId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrderId.setForeground(new java.awt.Color(0, 0, 0));
        lblOrderId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderId.setText("Order Id ");
        lblOrderId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, 90, -1));

        lblItemId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblItemId.setForeground(new java.awt.Color(0, 0, 0));
        lblItemId.setText("Item ID");
        add(lblItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        comboDiscription.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboDiscription.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDiscriptionItemStateChanged(evt);
            }
        });
        comboDiscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiscriptionActionPerformed(evt);
            }
        });
        add(comboDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 330, 40));

        btnAddToCart1.setBackground(new java.awt.Color(0, 0, 102));
        btnAddToCart1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddToCart1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart1.setText("Add to Cart");
        btnAddToCart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCart1ActionPerformed(evt);
            }
        });
        add(btnAddToCart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 160, 50));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Customer Contact");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Item ID");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        tblItemDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order ID", "Item", "Qty"
            }
        ));
        jScrollPane3.setViewportView(tblItemDetail);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 290, 250));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("User ID  :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("User ID  :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked

        try {
            ItemSearch item = new ItemSearch();
            item.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    }//GEN-LAST:event_btnSearchActionPerformed

    private void comboCustContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCustContactItemStateChanged

        try {
            String contact = (String) comboCustContact.getSelectedItem();
            Customer customer = new CustomerController().getCustomerName(contact);
            lblCustName.setText(customer.getCustId());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_comboCustContactItemStateChanged

    private void comboCustContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCustContactActionPerformed

    private void comboDiscriptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDiscriptionItemStateChanged
        try {
            String itemId = (String) comboDiscription.getSelectedItem();
            Items item = new ItemController().getItemId(itemId);
            lblItemId.setText(item.getItemId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboDiscriptionItemStateChanged

    private void comboDiscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiscriptionActionPerformed

    private void btnRomoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        int row = tbl1.getSelectedRow();
        if (row == -1) {
            return;
        }
        model.removeRow(row);

    }//GEN-LAST:event_btnRomoveActionPerformed

    private void btnAddToCart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCart1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        int qty = Integer.parseInt(txtQty.getText());

        int rowIndex = isAlreadyExsits(comboDiscription.getSelectedItem().toString());
        if (rowIndex == -1) {
            Object[] rowData = {
                comboDiscription.getSelectedItem().toString(),
                qty

            };
            model.addRow(rowData);
        } else {
            qty += (int) model.getValueAt(rowIndex, 1);

            tbl1.setValueAt(qty, rowIndex, 1);
        }

    }//GEN-LAST:event_btnAddToCart1ActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        try {
            String orderId = lblOrderId.getText();
            String userId = lblOrderId2.getText();
            String custId = lblCustName.getText();
            String date = "date";
            
            ArrayList <OrderDetail> list = new ArrayList<>();
            DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String itemId = lblItemId.getText();
                int qty = (int) model.getValueAt(i, 1);
                OrderDetail orderDetail = new OrderDetail(orderId, itemId, qty);
                list.add(orderDetail);
            }
            Order order = new Order(orderId,userId,custId,date,list);
            
            boolean isSaved = new OrderController().placeOrder(order);
            
            if (isSaved) {
                JOptionPane.showMessageDialog(this, "Order Placed");
                getLastId();
                
                tbl1.removeAll();
            } else {
                JOptionPane.showMessageDialog(this, "error");
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void tblordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblordersMouseClicked

        try {
            
            int i = tblorders.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblorders.getModel();
            lblOrder.setText(model.getValueAt(i, 0).toString());
            
            DefaultTableModel model1 = (DefaultTableModel) tblItemDetail.getModel();
            for(OrderDetail detail : new OrderDetailController().getItems(lblOrder.getText())){
                
               model1.addRow(new Object[]{
                detail.getOrderId(),
                detail.getItemId(),
                detail.getQty()
            });
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_tblordersMouseClicked
    public int isAlreadyExsits(String name) {
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String temp = model.getValueAt(i, 0).toString();
            if (temp.equalsIgnoreCase(name)) {
                return i;
            }
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart1;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRomove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboCustContact;
    private javax.swing.JComboBox<String> comboDiscription;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderId;
    public static javax.swing.JLabel lblOrderId2;
    private javax.swing.JSeparator lblOrdered;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tblItemDetail;
    private javax.swing.JTable tblorders;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void loadContact() throws ClassNotFoundException, SQLException {
        for (String temp : new CustomerController().getAllContact()) {
            comboCustContact.addItem(temp);
        }
    }

    private void loadDescription() throws ClassNotFoundException, SQLException {
        for (String temp : new ItemController().getDescription()) {
            comboDiscription.addItem(temp);
        }
    }

    private void getLastId() throws ClassNotFoundException, SQLException {
        String id = new OrderController().getLastOrderId();
        if (id == null) {
            lblOrderId.setText("OI0001");
        } else {
            String split[] = id.split("OI");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                lblOrderId.setText("OI000" + num);
            } else if (num < 100) {
                lblOrderId.setText("OI00" + num);
            } else if (num < 1000) {
                lblOrderId.setText("OI0" + num);
            } else {
                lblOrderId.setText("OI" + num);
            }
        }

    }

    private void loadAlOrders() throws ClassNotFoundException, SQLException {
        DefaultTableModel model = (DefaultTableModel) tblorders.getModel();
        for(Order order : new OrderController().getAllOrders()){
            model.addRow(new Object[]{
                order.getOrderId(),
                order.getUserId(),
                order.getDate()
            });
        }
    }

}
