/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.controller.CustomerController;
import lk.ijse.controller.DiscountController;
import lk.ijse.controller.InvoiceController;
import lk.ijse.controller.ItemController;
import lk.ijse.controller.OrderController;
import lk.ijse.controller.OrderDetailController;
import lk.ijse.model.CashDiscount;
import lk.ijse.model.Customer;
import lk.ijse.model.Invoice;
import lk.ijse.model.InvoiceDetail;
import lk.ijse.model.Items;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kushantha
 */
public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    public PayBill() throws ClassNotFoundException, SQLException {
        initComponents();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        Toolkit tool = Toolkit.getDefaultToolkit();
//        Dimension dm = new Dimension(tool.getScreenSize());
//        int height = (int) dm.getHeight();
//        int weight = (int) dm.getWidth();
//        setSize(weight,height);
//        setLocation(weight /2 - getWidth() / 2, height /2 - getHeight() /2);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadDiscount();
        loadInvoiceId();
        loadDate();
        loadToTable();
        loadContact();
        AutoCompleteDecorator.decorate(comboContact);
        lblCustomerOrder.setVisible(false);
        tableSetting();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtARDiscount = new javax.swing.JTextField();
        rNo = new javax.swing.JRadioButton();
        rYes = new javax.swing.JRadioButton();
        lblCustomerOrder = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        txtBarcode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtOPrice = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblDiscount2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDescription = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblItemId = new javax.swing.JLabel();
        lblPName = new javax.swing.JLabel();
        lblUnitPrice = new javax.swing.JLabel();
        lblQtyOnHand = new javax.swing.JLabel();
        txtNetTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCardDiscount = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        comboContact = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblDiscount1 = new javax.swing.JLabel();
        lblDiscount3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPurchase = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        lblDiscount4 = new javax.swing.JLabel();
        lblDiscount5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtDayDiscount = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblDiscount6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bookshop Management System");

        jPanel1.setBackground(new java.awt.Color(30, 39, 46));
        jPanel1.setToolTipText("");
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        lblInvoice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoice.setText("Invoice Id");
        lblInvoice.setAlignmentX(0.5F);
        lblInvoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("net Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Id    :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 122)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("]");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("customer ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtARDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtARDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtARDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtARDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(txtARDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 160, -1));

        buttonGroup1.add(rNo);
        rNo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rNo.setForeground(new java.awt.Color(255, 255, 255));
        rNo.setText("No");
        rNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rNoMouseClicked(evt);
            }
        });
        jPanel1.add(rNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        buttonGroup1.add(rYes);
        rYes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rYes.setForeground(new java.awt.Color(255, 255, 255));
        rYes.setText("Yes");
        rYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rYesMouseClicked(evt);
            }
        });
        jPanel1.add(rYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        lblCustomerOrder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustomerOrder.setForeground(new java.awt.Color(204, 0, 0));
        lblCustomerOrder.setText("Customer Have Order");
        lblCustomerOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomerOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerOrderMouseClicked(evt);
            }
        });
        jPanel1.add(lblCustomerOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("customer have card");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Discription", "Qty", "unitPrice", "Our Price", "Total"
            }
        ));
        tbl.setRowHeight(20);
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 1410, 350));

        jPanel2.setBackground(new java.awt.Color(30, 39, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Item ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        txtItemId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtItemId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        txtBarcode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBarcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeActionPerformed(evt);
            }
        });
        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyReleased(evt);
            }
        });
        jPanel2.add(txtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 220, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Barcode");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        txtDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescription.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 190, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Q / Discount");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        txtUnitPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnitPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 50, 140, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Unit Price");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Amount");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 10, -1, -1));

        txtQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        jPanel2.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 140, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 51, 0));
        jLabel17.setText("=");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 40, 30, -1));

        txtAmount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 50, 150, 30));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Our U/Price");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        txtOPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtOPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOPrice.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtOPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOPriceActionPerformed(evt);
            }
        });
        txtOPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOPriceKeyReleased(evt);
            }
        });
        jPanel2.add(txtOPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 120, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Qty");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        txtDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });
        jPanel2.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 120, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 40, 130, 50));

        lblDiscount2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount2.setForeground(new java.awt.Color(204, 51, 0));
        lblDiscount2.setText("*");
        jPanel2.add(lblDiscount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 43, 20, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1900, 120));

        jPanel3.setBackground(new java.awt.Color(30, 39, 46));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescription.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription.setText("Item Name");
        jPanel3.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 24, 470, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Item Id ");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 116, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Product Name");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 188, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Qty On Hand");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 331, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Unit Price");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 263, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 20, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(":");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 20, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 20, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText(":");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 20, -1));

        lblItemId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblItemId.setForeground(new java.awt.Color(255, 255, 255));
        lblItemId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemId.setText("N/A");
        jPanel3.add(lblItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 112, 210, -1));

        lblPName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPName.setForeground(new java.awt.Color(255, 255, 255));
        lblPName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPName.setText("N/A");
        lblPName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblPNameKeyReleased(evt);
            }
        });
        jPanel3.add(lblPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 188, 210, -1));

        lblUnitPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUnitPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblUnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnitPrice.setText("N/A");
        jPanel3.add(lblUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 263, 210, -1));

        lblQtyOnHand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblQtyOnHand.setForeground(new java.awt.Color(255, 255, 255));
        lblQtyOnHand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtyOnHand.setText("N/A");
        jPanel3.add(lblQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 331, 210, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 570, 470, 420));

        txtNetTotal.setBackground(new java.awt.Color(0, 204, 102));
        txtNetTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNetTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtNetTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNetTotal.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtNetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtNetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 140, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Purchase");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, -1, -1));

        txtCardDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCardDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtCardDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(txtCardDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 60, -1));

        txtBalance.setBackground(new java.awt.Color(0, 51, 255));
        txtBalance.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(0, 0, 0));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBalance.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 480, 160, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Balance");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 440, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText(":");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Invoice Id     :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Invoice Id");
        lblDate.setAlignmentX(0.5F);
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 150, -1));

        userName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Invoice Id");
        userName.setAlignmentX(0.5F);
        userName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 10, 150, -1));

        lblDiscount.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscount.setText("No Discount");
        jPanel1.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, 150, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1400, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1920, 10));

        txtTotal.setBackground(new java.awt.Color(255, 51, 51));
        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 160, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Have a Point");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        lblPoint.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPoint.setForeground(new java.awt.Color(0, 51, 204));
        lblPoint.setText("N/A");
        jPanel1.add(lblPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 60, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact Number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("N/A");
        lblId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdKeyReleased(evt);
            }
        });
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1920, 20));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Customer Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblCustName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustName.setText("N/A");
        jPanel1.add(lblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        comboContact.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comboContact.setForeground(new java.awt.Color(0, 0, 0));
        comboContact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select contact" }));
        comboContact.setEnabled(false);
        comboContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboContactItemStateChanged(evt);
            }
        });
        jPanel1.add(comboContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 246, 220, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Place Order");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 940, 140, 50));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 940, 130, 50));

        lblDiscount1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount1.setForeground(new java.awt.Color(204, 0, 0));
        lblDiscount1.setText("=");
        jPanel1.add(lblDiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 465, 30, -1));

        lblDiscount3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount3.setForeground(new java.awt.Color(204, 0, 0));
        lblDiscount3.setText("-");
        jPanel1.add(lblDiscount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 20, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("AR / disc");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 122)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("[");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        txtPurchase.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPurchase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPurchase.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchaseActionPerformed(evt);
            }
        });
        txtPurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPurchaseKeyPressed(evt);
            }
        });
        jPanel1.add(txtPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 160, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("C / disc");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 70, -1));

        lblDiscount4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount4.setForeground(new java.awt.Color(204, 0, 0));
        lblDiscount4.setText("+");
        jPanel1.add(lblDiscount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 465, 30, -1));

        lblDiscount5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount5.setForeground(new java.awt.Color(204, 0, 0));
        lblDiscount5.setText("-");
        jPanel1.add(lblDiscount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 20, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("D/disc");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 70, -1));

        txtDayDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDayDiscount.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtDayDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(txtDayDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 60, -1));

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSearch.setSelectionColor(new java.awt.Color(0, 0, 204));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 230, 150, 30));

        jPanel4.setBackground(new java.awt.Color(30, 39, 46));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTbl.setBackground(new java.awt.Color(30, 39, 46));
        searchTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchTbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchTbl.setForeground(new java.awt.Color(255, 255, 255));
        searchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Discripton", "qty", "Product", "UnitPrice", "Barcode"
            }
        ));
        searchTbl.setGridColor(new java.awt.Color(255, 255, 255));
        searchTbl.setRowHeight(25);
        searchTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(searchTbl);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, 239));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_search_32px.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 200, 490, 340));

        lblDiscount6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblDiscount6.setForeground(new java.awt.Color(204, 0, 0));
        lblDiscount6.setText("+");
        jPanel1.add(lblDiscount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 465, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void txtARDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtARDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtARDiscountActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed

    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void txtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarcodeActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtNetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetTotalActionPerformed

    private void txtCardDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardDiscountActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        try {
            DefaultTableModel model = (DefaultTableModel) searchTbl.getModel();
            model.setRowCount(0);

            for (Items temp : new ItemController().searchItems(txtSearch.getText())) {
                model.addRow(new Object[]{
                    temp.getItemId(),
                    temp.getDescription(),
                    temp.getQtyOnHand(),
                    temp.getPname(),
                    temp.getUnitPrice()

                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyReleased
        try {
            String barcode = txtBarcode.getText();
            Items item = new ItemController().getDetail(barcode);

            txtItemId.setText(item.getItemId());
            lblItemId.setText(item.getItemId());
            txtDescription.setText(item.getDescription());
            lblDescription.setText(item.getDescription());
            lblPName.setText(item.getPname());
            txtUnitPrice.setText(Double.toString(item.getUnitPrice()));
            lblUnitPrice.setText(Double.toString(item.getUnitPrice()));
            lblQtyOnHand.setText(Integer.toString(item.getQtyOnHand()));
//            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBarcodeKeyReleased

    private void lblPNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblPNameKeyReleased

    }//GEN-LAST:event_lblPNameKeyReleased

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        try {
            String pName = lblPName.getText();
            String discount = new ItemController().getProduct(pName);
            txtDiscount.setText(discount);

            if (txtDiscount != null) {
                double unitPrice = Double.parseDouble(txtUnitPrice.getText());
                double discount2 = Double.parseDouble(txtDiscount.getText());
                double total = (unitPrice * (100 - discount2)) / 100;
                txtOPrice.setText(Double.toString(total));

                double unitPrice2 = Double.parseDouble(txtOPrice.getText());
                int qty = Integer.parseInt(txtQty.getText());
                double total1 = unitPrice2 * qty;
                txtAmount.setText(Double.toString(total1));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtOPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOPriceActionPerformed

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased

    }//GEN-LAST:event_txtDiscountKeyReleased

    private void txtOPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOPriceKeyReleased

    }//GEN-LAST:event_txtOPriceKeyReleased

    private void searchTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTblMouseClicked
        int i = searchTbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) searchTbl.getModel();
        txtItemId.setText(model.getValueAt(i, 0).toString());
        lblItemId.setText(model.getValueAt(i, 0).toString());
        txtDescription.setText(model.getValueAt(i, 1).toString());
        lblDescription.setText(model.getValueAt(i, 1).toString());
        lblPName.setText(model.getValueAt(i, 3).toString());
        lblUnitPrice.setText(model.getValueAt(i, 4).toString());
        txtUnitPrice.setText(model.getValueAt(i, 4).toString());
        lblQtyOnHand.setText(model.getValueAt(i, 2).toString());
        txtBarcode.setText(model.getValueAt(i, 5).toString());

    }//GEN-LAST:event_searchTblMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int qty = Integer.parseInt(txtQty.getText());
        double ourPrice = Double.parseDouble(txtOPrice.getText());
        double unitPrice = Double.parseDouble(txtUnitPrice.getText());
        double total = Double.parseDouble(txtAmount.getText());
        int rowIndex = isAlreadyExists(txtItemId.getText());
        if (rowIndex == -1) {
            Object[] rowData = {
                txtItemId.getText(),
                txtDescription.getText(),
                qty,
                unitPrice,
                ourPrice,
                total
            };
            model.addRow(rowData);
        } else {
            qty += (int) model.getValueAt(rowIndex, 2);
            total += (double) model.getValueAt(rowIndex, 5);
            tbl.setValueAt(qty, rowIndex, 2);
            tbl.setValueAt(total, rowIndex, 5);
        }
        calculateTotal();
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboContactItemStateChanged
        try {
            String contact = (String) comboContact.getSelectedItem();
            Customer customer = new CustomerController().getCustomerName(contact);
            lblCustName.setText(customer.getCustname());
            lblId.setText(customer.getCustId());

            String id = lblId.getText();
            int count = new OrderController().countCustomerOrders(id);
            if (count != 0) {
                lblCustomerOrder.setText("This customer have " + count + " Orders");
                lblCustomerOrder.setVisible(true);
            } else {
                lblCustomerOrder.setVisible(false);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboContactItemStateChanged

    private void lblIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdKeyReleased

    }//GEN-LAST:event_lblIdKeyReleased

    private void lblCustomerOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerOrderMouseClicked

    }//GEN-LAST:event_lblCustomerOrderMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String invoiceId = lblInvoice.getText();
        String user = userName.getText();
        String status = "no";
        String custId = lblId.getText();

        ArrayList<InvoiceDetail> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        double total = Double.parseDouble(txtTotal.getText());
        for (int i = 0; i < model.getRowCount(); i++) {
            String itemId = (String) model.getValueAt(i, 0);
            double unitPrice = (double) model.getValueAt(i, 3);
            int qty = (int) model.getValueAt(i, 2);
            double ourPrice = (double) model.getValueAt(i, 4);
            InvoiceDetail inDetail = new InvoiceDetail(invoiceId, itemId, qty, unitPrice, ourPrice);
            list.add(inDetail);
        }

        if (rYes.isSelected()) {
            try {
                double point = Double.parseDouble(lblPoint.getText());
                Invoice invoice = new Invoice(invoiceId, custId, user, total, list);
                boolean isSaved = new InvoiceController().placeBill1(invoice);
                if (isSaved) {
                    JOptionPane.showMessageDialog(this, "Bill Placed");
                    loadInvoiceId();
                
                    clear2();
                    boolean isUpdatePoint = new CustomerController().updatePoint(point, custId);
                    
                    String searchOrder = new OrderController().searchOrders(custId);
                    if (searchOrder != null) {
                        boolean searchItem = new OrderDetailController().searchItem(searchOrder);

                        if (searchItem != false) {
                            boolean deleteOrders = new OrderController().deleteOrders(searchOrder);

                        }
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Error");
                }
            } catch (SQLException ex) {
                Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (rNo.isSelected()) {
            try {
                Invoice invoice = new Invoice(invoiceId, status, user, total, list);
                boolean isSaved = new InvoiceController().placeBill2(invoice);
                if (isSaved) {
                    JOptionPane.showMessageDialog(this, "Bill Placed");
                    loadInvoiceId();
                   
                    clear2();
                }

            } catch (SQLException ex) {
                Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        int row = tbl.getSelectedRow();
        if (row == -1) {
            return;
        }
        model.removeRow(row);
        calculateTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        try {
            for (CashDiscount range1 : new DiscountController().getRange1()) {
                double cash1 = range1.getCash();
                double discount1 = range1.getDiscount();

                for (CashDiscount range2 : new DiscountController().getRange2()) {
                    double cash2 = range2.getCash();
                    double discount2 = range2.getDiscount();

                    for (CashDiscount range3 : new DiscountController().getRange3()) {
                        double cash3 = range3.getCash();
                        double discount3 = range3.getDiscount();

                        String cardDiscount = new DiscountController().getCardDiscount();
                        txtCardDiscount.setText(cardDiscount);

                        double total = Double.parseDouble(txtTotal.getText());
                        if (total >= cash1 && total < cash2) {
                            double aRD1 = total * discount1 / 100;
                            txtARDiscount.setText(Double.toString(aRD1));
                            double netTotal = total - aRD1;
                            txtNetTotal.setText(Double.toString(netTotal));
                        } else if (total >= cash2 && total < cash3) {
                            double aRD2 = total * discount2 / 100;
                            txtARDiscount.setText(Double.toString(aRD2));
                            double netTotal2 = total - aRD2;
                            txtNetTotal.setText(Double.toString(netTotal2));
                        } else if (total > cash3) {
                            double aRD3 = total * discount3 / 100;
                            txtARDiscount.setText(Double.toString(aRD3));
                            double netTotal3 = total - aRD3;
                            txtNetTotal.setText(Double.toString(netTotal3));
                        } else {
                            txtNetTotal.setText(txtTotal.getText());

                        }
                    }
                }
            }
            String date = loadDate();
            String month = loadMonth();
            String checkDate = new DiscountController().getDayDiscount(date);
            String checkMonth = new DiscountController().getMothDiscount(month);
            if (checkDate != null) {
                double discount = Double.parseDouble(lblDiscount.getText());
                double total = Double.parseDouble(txtTotal.getText());
                double cashDisc = total * discount / 100;
                double netTotal = total * (100 - discount) / 100;
                txtNetTotal.setText(Double.toString(netTotal));
                txtDayDiscount.setText(Double.toString(cashDisc));

            } else if (checkMonth != null) {
                double discount = Double.parseDouble(lblDiscount.getText());
                double total = Double.parseDouble(txtTotal.getText());
                double netTotal = total * (100 - discount) / 100;
                txtNetTotal.setText(Double.toString(netTotal));
                double cashDisc = total * discount / 100;
                txtDayDiscount.setText(Double.toString(cashDisc));
            }

            String discount = new DiscountController().getCardDiscount();
            if (discount != null) {
                double value = Double.parseDouble(discount);
                if (value != 0) {
                    double total = Double.parseDouble(txtTotal.getText());
                    double netTotal = total * (100 - value) / 100;
                    txtNetTotal.setText(Double.toString(netTotal));
                    double cardDiscount = total * value / 100;
                    txtCardDiscount.setText(Double.toString(cardDiscount));
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(PayBill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchaseActionPerformed
        double purchase = Double.parseDouble(txtPurchase.getText());
        double netTotal = Double.parseDouble(txtNetTotal.getText());
        String total = new DecimalFormat("0.00").format(purchase - netTotal);

        txtBalance.setText(total);

        if (rYes.isSelected()) {
            double temp = Double.parseDouble(txtNetTotal.getText());
            String point = new DecimalFormat("0.00").format(temp / 17);
            lblPoint.setText(point);
        }
    }//GEN-LAST:event_txtPurchaseActionPerformed

    private void txtDayDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayDiscountActionPerformed

    private void txtPurchaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPurchaseKeyPressed


    }//GEN-LAST:event_txtPurchaseKeyPressed

    private void rYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rYesMouseClicked
        if (rYes.isSelected()) {
            comboContact.setEnabled(true);
            lblPoint.setEnabled(true);
        }
    }//GEN-LAST:event_rYesMouseClicked

    private void rNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rNoMouseClicked
        if (rNo.isSelected()) {
            comboContact.setEnabled(false);
            lblPoint.setEnabled(false);
        }
    }//GEN-LAST:event_rNoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        tbl.removeAll();
    }//GEN-LAST:event_jButton2MouseClicked

    public int isAlreadyExists(String id) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String temp = model.getValueAt(i, 0).toString();
            if (temp.equalsIgnoreCase(id)) {
                return i;
            }
        }
        return -1;
    }

    public void calculateTotal() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        double total = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (double) model.getValueAt(i, 5);

        }
        txtTotal.setText(String.valueOf(total));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBill.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBill.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBill.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBill.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PayBill().setVisible(true);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PayBill.class
                            .getName()).log(Level.SEVERE, null, ex);

                } catch (SQLException ex) {
                    Logger.getLogger(PayBill.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboContact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblCustomerOrder;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscount1;
    private javax.swing.JLabel lblDiscount2;
    private javax.swing.JLabel lblDiscount3;
    private javax.swing.JLabel lblDiscount4;
    private javax.swing.JLabel lblDiscount5;
    private javax.swing.JLabel lblDiscount6;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JLabel lblQtyOnHand;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JRadioButton rNo;
    private javax.swing.JRadioButton rYes;
    private javax.swing.JTable searchTbl;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtARDiscount;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtCardDiscount;
    private javax.swing.JTextField txtDayDiscount;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtNetTotal;
    private javax.swing.JTextField txtOPrice;
    private javax.swing.JTextField txtPurchase;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnitPrice;
    public static javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
    private String loadDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String date2 = dateFormat.format(date);
        lblDate.setText(date2);
        return date2;
    }

    private String loadMonth() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("M");
        String date2 = dateFormat.format(date);
        return date2;
    }

    private void loadDiscount() throws ClassNotFoundException, SQLException {
        String date = loadDate();
        String month = loadMonth();
        String checkDate = new DiscountController().getDayDiscount(date);
        String checkMonth = new DiscountController().getMothDiscount(month);

//        double monthDiscount = 0;
        if (checkMonth != null) {
            double x = Double.parseDouble(checkMonth);
            lblDiscount.setText(Double.toString(x));

        } else if (checkDate != null) {
            double x = Double.parseDouble(checkDate);
            lblDiscount.setText(Double.toString(x));

        }
//            lblDiscount.setText(checkMonth);
//
//            double totaldiscount = dateDiscount + monthDiscount;
//            txtDayDiscount.setText(Double.toString(totaldiscount));
//            titleDiscount.setText(Double.toString(totaldiscount));

    }

    private void loadInvoiceId() throws ClassNotFoundException, SQLException {
        String invoiceId = new InvoiceController().getLastId();
        if (invoiceId == null) {
            lblInvoice.setText("ID0000001");
        } else {
            String split[] = invoiceId.split("ID");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                lblInvoice.setText("ID000000" + num);
            } else if (num < 100) {
                lblInvoice.setText("ID00000" + num);
            } else if (num < 1000) {
                lblInvoice.setText("ID0000" + num);
            } else if (num < 10000) {
                lblInvoice.setText("ID000" + num);
            } else if (num < 100000) {
                lblInvoice.setText("ID00" + num);
            } else if (num < 1000000) {
                lblInvoice.setText("ID0" + num);
            } else if (num < 1000000) {
                lblInvoice.setText("ID" + num);
            }
        }
    }

    private void loadToTable() throws ClassNotFoundException, SQLException {
        DefaultTableModel model = (DefaultTableModel) searchTbl.getModel();
        for (Items item : new ItemController().getAllItems()) {
            model.addRow(new Object[]{
                item.getItemId(),
                item.getDescription(),
                item.getQtyOnHand(),
                item.getPname(),
                item.getUnitPrice(),
                item.getBarcode()

            });
        }
    }

    private void clear() {
        txtItemId.setText("");
        txtBarcode.setText("");
        txtDescription.setText("");
        txtOPrice.setText("");
        txtQty.setText("");
        txtUnitPrice.setText("");
        txtAmount.setText("");
        txtDiscount.setText("");
    }

    private void loadContact() throws ClassNotFoundException, SQLException {
        for (String customer : new CustomerController().getAllContact()) {
            comboContact.addItem(customer);
        }
    }

    private void tableSetting() {
        searchTbl.setShowGrid(true);
        tbl.setShowGrid(true);
    }

    public void clearRadioButton() {
        if(rYes.isSelected()){
            rYes.setSelected(false);
        }else{
        
        rNo.setSelected(false);
        }
    }

    private void clear2() {
        lblCustName.setText("N/A");
        lblId.setText("N/A");
        lblPoint.setText("N/A");
        txtTotal.setText("");
        txtARDiscount.setText("");
        txtCardDiscount.setText("");
        txtNetTotal.setText("");
        txtPurchase.setText("");
        txtBalance.setText("");
        clearRadioButton();
        lblItemId.setText("Item Name");
        lblDescription.setText("N/A");
        lblQtyOnHand.setText("N/A");
        lblPName.setText("N/A");
        lblUnitPrice.setText("N/A");
        
    }
}
