/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import lk.ijse.controller.ItemController;
import lk.ijse.model.Data;

/**
 *
 * @author kushantha
 */
public class SuplierReport extends javax.swing.JPanel {

    /**
     * Creates new form SuplierReport
     */
    public SuplierReport() {
        try {
            initComponents();
            loadAllDetail();
            txtSearch.setBackground(new Color(0, 0, 0, 64));
            
         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuplierReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuplierReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 51, 107));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suplier ID", "Suplier name", "Product name", "Description", "Available Qty", "Bought Qty", "suply Date", "Amount"
            }
        ));
        tbl.setRowHeight(20);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 960, 520));

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/icons8_search_32px.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 45, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/view/pictures/icons8_books_96px.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supplier Report");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        
        try {
            DefaultTableModel model = (DefaultTableModel) tbl.getModel();
            model.setRowCount(0);

            for (Data temp : new ItemController().searchData(txtSearch.getText())) {
                model.addRow(new Object[]{
                    temp.getSupId(),
                    temp.getSupName(),
                    temp.getpName(),
                    temp.getDiscription(),
                    temp.getAvailableQty(),
                    temp.getBoughtQty(),
                    temp.getSupDate(),
                    temp.getPtotal()

                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuplierReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuplierReport.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        

    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadAllDetail() throws ClassNotFoundException, SQLException {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        for (Data data : new ItemController().getAllData()) {
            model.addRow(new Object[]{
                data.getSupId(),
                data.getSupName(),
                data.getpName(),
                data.getDiscription(),
                data.getAvailableQty(),
                data.getBoughtQty(),
                data.getSupDate(),
                data.getPtotal()

            });
        }
    }
}
